# Generated by Django 5.0.7 on 2024-08-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_rename_course_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Course_id',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
