# Generated by Django 5.0.7 on 2024-08-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_rename_session_starts_year_students_session_start_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_start_year',
            new_name='session_starts_year',
        ),
    ]
